# 时间日期格式化
spring:
  mvc:
    date-format: yyyy-MM-dd

  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: top.aegean19.springboot05mybatis.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml